Kprawat
vishnuchalla/chat-defender-bot pull request #8
Opened 2022-12-03 20:58 UTC by kanchan110295

Kindly review the changes and merge them

2022-12-03 21:12 UTC, svnsairam requested changes
This commit is failing,  check and create a new pull request

2022-12-03 22:12 UTC, vishnuchalla reviewed
Good to fly.

2022-12-03 22:12 UTC, vishnuchalla commented on src/run.py
> +    if msg_content.lower().find('hello') or msg_content.lower().find('hi') or msg_content.lower().find('hey') != -1:
nice checks. good catch

2022-12-04 14:03 UTC, vishnuchalla approved these changes

2022-12-04 14:03 UTC, vishnuchalla reviewed
Resolve the conflicts and update the PR

2022-12-04 19:27 UTC, merged